apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: staging
type: Opaque
data:
  # these values must be base64-encoded
  username: ZGV2b3BzZXI=        # base64 of "devopser"
  password: QWRtaW4xMjMK         # base64 of "Admin123"
  database: Zmxhc2hkYg==         # base64 of "flaskdb"
