stages:
  - test
  - build

# -------- TEST STAGE --------
test:
  stage: test
  image: python:3.12
  before_script:
    - pip install pytest pytest-cov
    - pip install flask==1.1.2 jinja2==3.0.3 itsdangerous==2.0.1 werkzeug==1.0.1
  script:
    - cd app
    - pytest --cov=app tests/

# -------- BUILD STAGE --------
variables:
  IMAGE_NAME: registry.internal.uia.no/ikt206-g-25v-devops/group23/exam-ikt206/flask-example-staging

build-image:
  stage: build
  image: gcr.io/kaniko-project/executor:latest
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/flask-example-staging
    DOCKERFILE_PATH: ci-cd/Dockerfile
  script:
    - |
      /kaniko/executor \
        --context $CI_PROJECT_DIR \
        --dockerfile $DOCKERFILE_PATH \
        --destination $IMAGE_NAME \
        --insecure \
        --skip-tls-verify \
        --cache=false

