stages:
  - test
  - build
  - deploy-staging
  - deploy-production

variables:
  # Use immutable tags per commit
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  REGISTRY: registry.internal.uia.no/ikt206-g-25v-devops/group23/exam-ikt206
  STAGING_IMAGE: $REGISTRY/flask-example-staging:v1.5
  PROD_IMAGE:    $REGISTRY/flask-example-production:v1.5

# -------- TEST STAGE --------
test:
  stage: test
  image: python:3.12
  before_script:
    - pip install -r app/requirements.txt
    - pip install pytest pytest-cov
  script:
    - cd app
    - pytest --cov=app tests/

# -------- BUILD & PUSH DOCKER IMAGE --------
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    # configure Kaniko to push into our registry
    - mkdir -p /kaniko/.docker
    - |
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" \
        > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context="$CI_PROJECT_DIR" \
        --dockerfile="$CI_PROJECT_DIR/ci-cd/Dockerfile" \
        --destination="$STAGING_IMAGE" \
        --destination="$PROD_IMAGE" \
        --verbosity=info

# -------- DEPLOY TO STAGING (manual) --------
deploy-staging:
  stage: deploy-staging
  when: manual
  image: bitnami/kubectl:1.27
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_CONTENT" > ~/.kube/config
  script:
    - sed -i "s|IMAGE_PLACEHOLDER|$STAGING_IMAGE|g" k8s/staging/deployment.yaml
    - kubectl apply -f k8s/staging/namespace.yaml --validate=false
    - kubectl apply -f k8s/staging/service.yaml   --validate=false
    - kubectl apply -f k8s/staging/deployment.yaml --validate=false
  environment:
    name: staging
    url: http://$STAGING_HOST
  only:
    - main

# -------- DEPLOY TO PRODUCTION (manual) --------
deploy-production:
  stage: deploy-production
  when: manual
  image: bitnami/kubectl:1.27
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_CONTENT" > ~/.kube/config
  script:
    - sed -i "s|IMAGE_PLACEHOLDER|$PROD_IMAGE|g" k8s/production/deployment.yaml
    - kubectl apply -f k8s/production/namespace.yaml --validate=false
    - kubectl apply -f k8s/production/service.yaml   --validate=false
    - kubectl apply -f k8s/production/deployment.yaml --validate=false
  environment:
    name: production
    url: http://$PROD_HOST
  only:
    - main
