apiVersion: v1
kind: Service
metadata:
  name: postgres-production
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: postgres-production
  ports:
    - port: 5432
      targetPort: 5432