apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-example
  namespace: staging
  annotations:
    # Tell Image Updater which image(s) to track
    argocd-image-updater.argoproj.io/image-list: |
      flask-example=registry.internal.uia.no/ikt206-g-25v-devops/group23/exam-ikt206/flask-example-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-example
  template:
    metadata:
      labels:
        app: flask-example
    spec:
      imagePullSecrets:
        - name: gitlab-registry-auth
      securityContext:
        runAsNonRoot: true
      containers:
        - name: flask-example
          image: IMAGE_PLACEHOLDER       # ← replaced by CI
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:p0BHJJoNqz@postgres-staging-postgresql:5432/flaskdb
