apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-staging
  template:
    metadata:
      labels:
        app: postgres-staging
    spec:
      securityContext:
        runAsNonRoot: true
        fsGroup: 999              # ← ensures the PVC mount is chowned to GID 999
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-staging-pvc
