apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-production
  namespace: production
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0          # no extra pods
      maxUnavailable: 1
  selector:
    matchLabels:
      app: postgres-production
  template:
    metadata:
      labels:
        app: postgres-production
    spec:
      # Pod-level securityContext for restricted policy
      securityContext:
        runAsNonRoot: true           # Deny running as root
        runAsUser: 1000              # Pick a non-root UID
        fsGroup: 2000                # Ensure mounted volumes are writable
        seccompProfile:
          type: RuntimeDefault      # Use Docker’s default seccomp profile

      containers:
        - name: postgres
          image: postgres:14-alpine
          ports:
            - containerPort: 5432

          # Container-level securityContext
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
           # - name: PGDATA
            #  value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-production-pvc
