apiVersion: v1
kind: Service
metadata:
  name: postgres-production
  namespace: production
spec:
  type: ClusterIP           # Optional, ClusterIP is default
  selector:
    app: postgres           # MUST match pod label
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
