apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: production
type: Opaque
data:
  username: Zmxhc2td               # base64("flaskuser")
  password: QWRtaW4xMjM=           # base64("Admin123")
  database: Zmxhc2tkYg==           # base64("flaskdb")