apiVersion: v1
kind: Service
metadata:
  name: flask-example
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30864
  selector:
    app: flask-example
